### ISSUE TITLE
Example screenshots

### ISSUE THREAD

**Issue by dstollie** [darwinsalinas/laravel-permission-ui#1]
Do you have some example screenshots to show in the Readme? Would be handy to get a better idea of the features and the looks of this repo

**Comment by darwinsalinas** [comment]
no está terminado todavía, pero la idea es hacerlo con Bootstrap

**Comment by dstollie** [comment]
Translation if @darwinsalinas : "is not finished yet, but the idea is to do it with Bootstrap"

Ok thanks, next time it would be simpler to reply back in English.
